export const ALL_TOOL_NAMES = [
  "tripit_trips_list",
  "tripit_trips_get",
  "tripit_trips_create",
  "tripit_trips_update",
  "tripit_trips_delete",
  "tripit_hotels_get",
  "tripit_hotels_create",
  "tripit_hotels_update",
  "tripit_hotels_delete",
  "tripit_hotels_attach_document",
  "tripit_hotels_remove_document",
  "tripit_flights_get",
  "tripit_flights_create",
  "tripit_flights_update",
  "tripit_flights_delete",
  "tripit_transport_get",
  "tripit_transport_create",
  "tripit_transport_update",
  "tripit_transport_delete",
  "tripit_activities_get",
  "tripit_activities_create",
  "tripit_activities_update",
  "tripit_activities_delete",
  "tripit_documents_attach",
  "tripit_documents_remove",
  "tripit_unfiled_list",
  "tripit_unfiled_get",
  "tripit_unfiled_create",
  "tripit_unfiled_update",
  "tripit_unfiled_assign",
  "tripit_unfiled_delete",
] as const;

export type TripItToolName = (typeof ALL_TOOL_NAMES)[number];
