export const ALL_TOOL_NAMES = [
  "tripit_list_trips",
  "tripit_get_trip",
  "tripit_create_trip",
  "tripit_update_trip",
  "tripit_delete_trip",
  "tripit_get_lodging",
  "tripit_create_lodging",
  "tripit_update_lodging",
  "tripit_delete_lodging",
  "tripit_attach_lodging_document",
  "tripit_remove_lodging_document",
  "tripit_get_flight",
  "tripit_create_flight",
  "tripit_update_flight",
  "tripit_delete_flight",
  "tripit_get_transport",
  "tripit_create_transport",
  "tripit_update_transport",
  "tripit_delete_transport",
  "tripit_get_activity",
  "tripit_create_activity",
  "tripit_update_activity",
  "tripit_delete_activity",
  "tripit_attach_document",
  "tripit_remove_document",
  "tripit_get_trip_item",
  "tripit_create_trip_item",
  "tripit_list_unfiled_items",
  "tripit_get_unfiled_item",
  "tripit_create_item_without_trip",
  "tripit_replace_unfiled_item",
  "tripit_assign_unfiled_item",
  "tripit_convert_unfiled_item",
  "tripit_delete_unfiled_item",
] as const;

export type TripItToolName = (typeof ALL_TOOL_NAMES)[number];
